name: CD

on:
  push:
    branches:
      - development
      - feature/*
  pull_request:
      branches:
        - development

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        working-directory: ${{github.workspace}}/LawSociety.Server
        run: |
          docker build -f "${{github.workspace}}/LawSociety.Server/Dockerfile" --force-rm -t ${{ secrets.DOCKER_USERNAME }}/law-society:latest --target base  --build-arg "BUILD_CONFIGURATION=Debug" --label "com.microsoft.created-by=visual-studio" --label "com.microsoft.visual-studio.project-name=LawSociety.Server" "${{github.workspace}}/"

      - name: Push Docker Image
        working-directory: ${{github.workspace}}
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/law-society:latest