name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - deveopment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: dotnet test --no-restore --verbosity normal
